// flow-typed signature: 4d6c914f8ab1e2d94bcce9580bb2dd5e
// flow-typed version: <<STUB>>/@tensorflow/tfjs_v^0.13.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tensorflow/tfjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tensorflow/tfjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tensorflow/tfjs/dist-es6/index_test' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist-es6/index' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist-es6/version' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist/index' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist/tf.esm' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist/tf' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist/tf.min' {
  declare module.exports: any;
}

declare module '@tensorflow/tfjs/dist/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tensorflow/tfjs/dist-es6/index_test.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist-es6/index_test'>;
}
declare module '@tensorflow/tfjs/dist-es6/index.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist-es6/index'>;
}
declare module '@tensorflow/tfjs/dist-es6/version.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist-es6/version'>;
}
declare module '@tensorflow/tfjs/dist/index.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist/index'>;
}
declare module '@tensorflow/tfjs/dist/tf.esm.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist/tf.esm'>;
}
declare module '@tensorflow/tfjs/dist/tf.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist/tf'>;
}
declare module '@tensorflow/tfjs/dist/tf.min.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist/tf.min'>;
}
declare module '@tensorflow/tfjs/dist/version.js' {
  declare module.exports: $Exports<'@tensorflow/tfjs/dist/version'>;
}
