// flow-typed signature: f87405533767cc7101dcc0ae1793dc55
// flow-typed version: <<STUB>>/material-ui-color-picker_v^2.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-color-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-color-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-color-picker/lib/components/ColorPicker' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/lib/components/PickerDialog' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/lib/index' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/lib/transformers' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/src/components/ColorPicker' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/src/components/PickerDialog' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/src/index' {
  declare module.exports: any;
}

declare module 'material-ui-color-picker/src/transformers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-color-picker/lib/components/ColorPicker.js' {
  declare module.exports: $Exports<'material-ui-color-picker/lib/components/ColorPicker'>;
}
declare module 'material-ui-color-picker/lib/components/PickerDialog.js' {
  declare module.exports: $Exports<'material-ui-color-picker/lib/components/PickerDialog'>;
}
declare module 'material-ui-color-picker/lib/index.js' {
  declare module.exports: $Exports<'material-ui-color-picker/lib/index'>;
}
declare module 'material-ui-color-picker/lib/transformers.js' {
  declare module.exports: $Exports<'material-ui-color-picker/lib/transformers'>;
}
declare module 'material-ui-color-picker/src/components/ColorPicker.js' {
  declare module.exports: $Exports<'material-ui-color-picker/src/components/ColorPicker'>;
}
declare module 'material-ui-color-picker/src/components/PickerDialog.js' {
  declare module.exports: $Exports<'material-ui-color-picker/src/components/PickerDialog'>;
}
declare module 'material-ui-color-picker/src/index.js' {
  declare module.exports: $Exports<'material-ui-color-picker/src/index'>;
}
declare module 'material-ui-color-picker/src/transformers.js' {
  declare module.exports: $Exports<'material-ui-color-picker/src/transformers'>;
}
