// flow-typed signature: 09e97c85a52452910eb1f1f65e372ddc
// flow-typed version: <<STUB>>/raven-for-redux_v^1.3.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raven-for-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raven-for-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raven-for-redux/built/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raven-for-redux/built/index.js' {
  declare module.exports: $Exports<'raven-for-redux/built/index'>;
}
