// flow-typed signature: 61355c21be033a14d269cef88359b6b7
// flow-typed version: <<STUB>>/react-hotkeys_v^1.1.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hotkeys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hotkeys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hotkeys/cjs/FocusTrap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/FocusTrapHOC' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/HotKeyMapMixin' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/HotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/index' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/react-hotkeys.production.min' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/hasChanged' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/sequencesFromKeyMap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/withHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/FocusTrap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/FocusTrapHOC' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/HotKeyMapMixin' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/HotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/index' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/react-hotkeys.production.min' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/hasChanged' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/sequencesFromKeyMap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/withHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/examples/index' {
  declare module.exports: any;
}

declare module 'react-hotkeys/examples/master/index' {
  declare module.exports: any;
}

declare module 'react-hotkeys/index.es' {
  declare module.exports: any;
}

declare module 'react-hotkeys/lib/index' {
  declare module.exports: any;
}

declare module 'react-hotkeys/umd/react-hotkeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/umd/react-hotkeys.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hotkeys/cjs/FocusTrap.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/FocusTrap'>;
}
declare module 'react-hotkeys/cjs/FocusTrapHOC.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/FocusTrapHOC'>;
}
declare module 'react-hotkeys/cjs/HotKeyMapMixin.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/HotKeyMapMixin'>;
}
declare module 'react-hotkeys/cjs/HotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/HotKeys'>;
}
declare module 'react-hotkeys/cjs/index.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/index'>;
}
declare module 'react-hotkeys/cjs/react-hotkeys.production.min.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/react-hotkeys.production.min'>;
}
declare module 'react-hotkeys/cjs/utils/hasChanged.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/hasChanged'>;
}
declare module 'react-hotkeys/cjs/utils/sequencesFromKeyMap.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/sequencesFromKeyMap'>;
}
declare module 'react-hotkeys/cjs/withHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/withHotKeys'>;
}
declare module 'react-hotkeys/es/FocusTrap.js' {
  declare module.exports: $Exports<'react-hotkeys/es/FocusTrap'>;
}
declare module 'react-hotkeys/es/FocusTrapHOC.js' {
  declare module.exports: $Exports<'react-hotkeys/es/FocusTrapHOC'>;
}
declare module 'react-hotkeys/es/HotKeyMapMixin.js' {
  declare module.exports: $Exports<'react-hotkeys/es/HotKeyMapMixin'>;
}
declare module 'react-hotkeys/es/HotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/HotKeys'>;
}
declare module 'react-hotkeys/es/index.js' {
  declare module.exports: $Exports<'react-hotkeys/es/index'>;
}
declare module 'react-hotkeys/es/react-hotkeys.production.min.js' {
  declare module.exports: $Exports<'react-hotkeys/es/react-hotkeys.production.min'>;
}
declare module 'react-hotkeys/es/utils/hasChanged.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/hasChanged'>;
}
declare module 'react-hotkeys/es/utils/sequencesFromKeyMap.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/sequencesFromKeyMap'>;
}
declare module 'react-hotkeys/es/withHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/withHotKeys'>;
}
declare module 'react-hotkeys/examples/index.js' {
  declare module.exports: $Exports<'react-hotkeys/examples/index'>;
}
declare module 'react-hotkeys/examples/master/index.js' {
  declare module.exports: $Exports<'react-hotkeys/examples/master/index'>;
}
declare module 'react-hotkeys/index.es.js' {
  declare module.exports: $Exports<'react-hotkeys/index.es'>;
}
declare module 'react-hotkeys/index' {
  declare module.exports: $Exports<'react-hotkeys'>;
}
declare module 'react-hotkeys/index.js' {
  declare module.exports: $Exports<'react-hotkeys'>;
}
declare module 'react-hotkeys/lib/index.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/index'>;
}
declare module 'react-hotkeys/umd/react-hotkeys.js' {
  declare module.exports: $Exports<'react-hotkeys/umd/react-hotkeys'>;
}
declare module 'react-hotkeys/umd/react-hotkeys.min.js' {
  declare module.exports: $Exports<'react-hotkeys/umd/react-hotkeys.min'>;
}
