// flow-typed signature: fe5342ddb83d4f09c5c091a8dacfc908
// flow-typed version: <<STUB>>/react-grid-gallery_v^0.5.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-grid-gallery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-grid-gallery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-grid-gallery/examples/app' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/demo1' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/demo2' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/demo3' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/demo4' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/demo5' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/demo6' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/examples/different-orientations-example' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/gulpfile' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/lib/CheckButton' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/lib/Gallery' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/lib/Image' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/lib/react-grid-gallery.bundle.min' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/src/CheckButton' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/src/Gallery' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/src/Image' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-grid-gallery/examples/app.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/app'>;
}
declare module 'react-grid-gallery/examples/demo1.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/demo1'>;
}
declare module 'react-grid-gallery/examples/demo2.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/demo2'>;
}
declare module 'react-grid-gallery/examples/demo3.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/demo3'>;
}
declare module 'react-grid-gallery/examples/demo4.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/demo4'>;
}
declare module 'react-grid-gallery/examples/demo5.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/demo5'>;
}
declare module 'react-grid-gallery/examples/demo6.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/demo6'>;
}
declare module 'react-grid-gallery/examples/different-orientations-example.js' {
  declare module.exports: $Exports<'react-grid-gallery/examples/different-orientations-example'>;
}
declare module 'react-grid-gallery/gulpfile.js' {
  declare module.exports: $Exports<'react-grid-gallery/gulpfile'>;
}
declare module 'react-grid-gallery/lib/CheckButton.js' {
  declare module.exports: $Exports<'react-grid-gallery/lib/CheckButton'>;
}
declare module 'react-grid-gallery/lib/Gallery.js' {
  declare module.exports: $Exports<'react-grid-gallery/lib/Gallery'>;
}
declare module 'react-grid-gallery/lib/Image.js' {
  declare module.exports: $Exports<'react-grid-gallery/lib/Image'>;
}
declare module 'react-grid-gallery/lib/react-grid-gallery.bundle.min.js' {
  declare module.exports: $Exports<'react-grid-gallery/lib/react-grid-gallery.bundle.min'>;
}
declare module 'react-grid-gallery/src/CheckButton.js' {
  declare module.exports: $Exports<'react-grid-gallery/src/CheckButton'>;
}
declare module 'react-grid-gallery/src/Gallery.js' {
  declare module.exports: $Exports<'react-grid-gallery/src/Gallery'>;
}
declare module 'react-grid-gallery/src/Image.js' {
  declare module.exports: $Exports<'react-grid-gallery/src/Image'>;
}
