// flow-typed signature: 5ae4330cc4291aed1819c694c93154cd
// flow-typed version: <<STUB>>/react-image-lightbox_v^5.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-lightbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-lightbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-lightbox/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-lightbox/dist/main.js' {
  declare module.exports: $Exports<'react-image-lightbox/dist/main'>;
}
