// flow-typed signature: 717b18543c6c45768b7570dbbd82ea36
// flow-typed version: <<STUB>>/@material-ui/lab_v^3.0.0-alpha.20/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/lab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/lab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/lab/es/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/Add' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Slider/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Slider/Slider' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDial/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDial/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDial/utils' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialAction/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialAction/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialIcon/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialIcon/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButton/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButton/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup/hasValue' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup/isValueSelected' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/utils/clamp' {
  declare module.exports: any;
}

declare module '@material-ui/lab/index.es' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/Add' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Slider/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Slider/Slider' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDial/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDial/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDial/utils' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialAction/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialAction/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialIcon/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialIcon/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButton/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButton/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup/hasValue' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup/index' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup/isValueSelected' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/utils/clamp' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/lab/es/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/index'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/Add.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/Add'>;
}
declare module '@material-ui/lab/es/Slider/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Slider/index'>;
}
declare module '@material-ui/lab/es/Slider/Slider.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Slider/Slider'>;
}
declare module '@material-ui/lab/es/SpeedDial/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDial/index'>;
}
declare module '@material-ui/lab/es/SpeedDial/SpeedDial.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDial/SpeedDial'>;
}
declare module '@material-ui/lab/es/SpeedDial/utils.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDial/utils'>;
}
declare module '@material-ui/lab/es/SpeedDialAction/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialAction/index'>;
}
declare module '@material-ui/lab/es/SpeedDialAction/SpeedDialAction.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialAction/SpeedDialAction'>;
}
declare module '@material-ui/lab/es/SpeedDialIcon/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialIcon/index'>;
}
declare module '@material-ui/lab/es/SpeedDialIcon/SpeedDialIcon.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialIcon/SpeedDialIcon'>;
}
declare module '@material-ui/lab/es/ToggleButton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButton/index'>;
}
declare module '@material-ui/lab/es/ToggleButton/ToggleButton.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButton/ToggleButton'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/hasValue.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup/hasValue'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup/index'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/isValueSelected.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup/isValueSelected'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/es/utils/clamp.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/utils/clamp'>;
}
declare module '@material-ui/lab/index.es.js' {
  declare module.exports: $Exports<'@material-ui/lab/index.es'>;
}
declare module '@material-ui/lab/index' {
  declare module.exports: $Exports<'@material-ui/lab'>;
}
declare module '@material-ui/lab/index.js' {
  declare module.exports: $Exports<'@material-ui/lab'>;
}
declare module '@material-ui/lab/internal/svg-icons/Add.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/Add'>;
}
declare module '@material-ui/lab/Slider/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Slider/index'>;
}
declare module '@material-ui/lab/Slider/Slider.js' {
  declare module.exports: $Exports<'@material-ui/lab/Slider/Slider'>;
}
declare module '@material-ui/lab/SpeedDial/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial/index'>;
}
declare module '@material-ui/lab/SpeedDial/SpeedDial.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial/SpeedDial'>;
}
declare module '@material-ui/lab/SpeedDial/utils.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial/utils'>;
}
declare module '@material-ui/lab/SpeedDialAction/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialAction/index'>;
}
declare module '@material-ui/lab/SpeedDialAction/SpeedDialAction.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialAction/SpeedDialAction'>;
}
declare module '@material-ui/lab/SpeedDialIcon/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialIcon/index'>;
}
declare module '@material-ui/lab/SpeedDialIcon/SpeedDialIcon.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialIcon/SpeedDialIcon'>;
}
declare module '@material-ui/lab/ToggleButton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButton/index'>;
}
declare module '@material-ui/lab/ToggleButton/ToggleButton.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButton/ToggleButton'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/hasValue.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup/hasValue'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup/index'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/isValueSelected.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup/isValueSelected'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/utils/clamp.js' {
  declare module.exports: $Exports<'@material-ui/lab/utils/clamp'>;
}
