export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const UPDATE_CATEGORY_DESCRIPTION = 'UPDATE_CATEGORY_DESCRIPTION';

export const UPDATE_CATEGORY_VISIBILITY = 'UPDATE_CATEGORY_VISIBILITY';

export const CREATE_IMAGE = 'CREATE_IMAGE';

export const DELETE_IMAGE = 'DELETE_IMAGE';

export const UPDATE_IMAGE_CATEGORY = 'UPDATE_IMAGE_CATEGORY';

export const UPDATE_SETTING_COLUMNS = 'UPDATE_SETTING_COLUMNS';

export const UPDATE_SETTING_SIDEBAR_OPEN = 'UPDATE_SETTING_SIDEBAR_OPEN';

export const FIT_CLASSIFIER = 'FIT_CLASSIFIER';

export const OPEN_CLASSIFIER = 'OPEN_CLASSIFIER';

export const SAVE_CLASSIFIER = 'SAVE_CLASSIFIER';
