export const ADD_CATEGORIES = 'ADD_CATEGORIES';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const UPDATE_CATEGORY_DESCRIPTION = 'UPDATE_CATEGORY_DESCRIPTION';

export const UPDATE_CATEGORY_VISIBILITY = 'UPDATE_CATEGORY_VISIBILITY';

export const CREATE_IMAGE = 'CREATE_IMAGE';

export const DELETE_IMAGE = 'DELETE_IMAGE';

export const ADD_IMAGES = 'ADD_IMAGES';

export const UPDATE_PROBABILITY = 'UPDATE_PROBABILITY';

export const UPDATE_IMAGE_CATEGORY = 'UPDATE_IMAGE_CATEGORY';

export const UPDATE_IMAGES_HAVING_CERTAIN_CATEGORY =
  'UPDATE_IMAGES_HAVING_CERTAIN_CATEGORY';

export const UPDATE_SETTING_COLUMNS = 'UPDATE_SETTING_COLUMNS';

export const UPDATE_SETTING_SIDEBAR_OPEN = 'UPDATE_SETTING_SIDEBAR_OPEN';

export const FIT_CLASSIFIER = 'FIT_CLASSIFIER';

export const CLASSIFIER_OPEN = 'CLASSIFIER_OPEN';

export const CLASSIFIER_SAVE = 'CLASSIFIER_SAVE';

export const OPEN_SETTINGS_DIALOG = 'OPEN_SETTINGS_DIALOG';

export const CLOSE_SETTINGS_DIALOG = 'CLOSE_SETTINGS_DIALOG';

export const OPEN_CREATE_CATEGORY_DIALOG = 'OPEN_CREATE_CATEGORY_DIALOG';

export const CLOSE_CREATE_CATEGORY_DIALOG = 'CLOSE_CREATE_CATEGORY_DIALOG';

export const TOGGLE_CREATE_CATEGORY_COLOR_MENU =
  'TOGGLE_CREATE_CATEGORY_COLOR_MENU';

export const TOGGLE_HELP_DIALOG = 'TOGGLE_HELP_DIALOG';
