// flow-typed signature: 118f6ce083ec1c4931d1bca4fccac849
// flow-typed version: <<STUB>>/@axetroy/react-download_v^1.1.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@axetroy/react-download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@axetroy/react-download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@axetroy/react-download/lib/react-download' {
  declare module.exports: any;
}

declare module '@axetroy/react-download/webpack.config.dev' {
  declare module.exports: any;
}

declare module '@axetroy/react-download/webpack.config.doc' {
  declare module.exports: any;
}

declare module '@axetroy/react-download/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module '@axetroy/react-download/index' {
  declare module.exports: $Exports<'@axetroy/react-download'>;
}
declare module '@axetroy/react-download/index.js' {
  declare module.exports: $Exports<'@axetroy/react-download'>;
}
declare module '@axetroy/react-download/lib/react-download.js' {
  declare module.exports: $Exports<'@axetroy/react-download/lib/react-download'>;
}
declare module '@axetroy/react-download/webpack.config.dev.js' {
  declare module.exports: $Exports<'@axetroy/react-download/webpack.config.dev'>;
}
declare module '@axetroy/react-download/webpack.config.doc.js' {
  declare module.exports: $Exports<'@axetroy/react-download/webpack.config.doc'>;
}
declare module '@axetroy/react-download/webpack.config.prod.js' {
  declare module.exports: $Exports<'@axetroy/react-download/webpack.config.prod'>;
}
