// flow-typed signature: 1c3cbb9b3cdbffad4569e64e59d0657e
// flow-typed version: <<STUB>>/@storybook/addons_v^3.4.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addons/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addons/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addons/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/index'>;
}
declare module '@storybook/addons/src/index.js' {
  declare module.exports: $Exports<'@storybook/addons/src/index'>;
}
